### ISSUE TITLE
Work with Babel

### ISSUE THREAD

**Issue by daniloprates** [TrySound/rollup-plugin-uglify#10]
How would I work with Babel?

**Comment by TrySound** [comment]
Just add in transformBundle transform with babili preset and prevent looking for babelrc. Look at this plugin and rollup-plugin-babel.

**Comment by TrySound** [comment]
Just add in transformBundle transform with babili preset and prevent looking for babelrc. Look at this plugin and rollup-plugin-babel.

**Comment by daniloprates** [comment]
I've managed to do it just by calling babel before rollup-plugin-uglify. Not sure if that would be unsafe, though:

```js
import babel from 'rollup-plugin-babel';
import uglify from 'rollup-plugin-uglify';

export default {
  entry: 'src/main.js',
  format: 'cjs',
  plugins: [ babel(), uglify() ],
  dest: 'bundle.js'
};
```

**Comment by TrySound** [comment]
Ah, you are about it. It's fine. What is the problem? Uglify with `transformBundle` is always called after babel with it `transform` hook.
