### ISSUE TITLE
comments for licensing

### ISSUE THREAD

**Issue by yairEO** [TrySound/rollup-plugin-uglify#12]
Hey Bogdan, regarding what you've mentioned in README, I was wondering. a code can have thousands upon thousands of comments. check each for the single one which is your license seems to me harmful for performance. 

Wouldn't it be better to pass an option to leave alone on the **first** comment? 
The first comment is almost always the license comment.

**Comment by TrySound** [comment]
Hi! This callback is processed by uglify. Uglify API seems do not let to control this. So, nothing I can do. You may report this issue in uglify repo.

**Comment by yairEO** [comment]
Thanks I will do that
