### ISSUE TITLE
Cannot preserve first comment

### ISSUE THREAD

**Issue by Grawl** [TrySound/rollup-plugin-uglify#15]
I am using a simple gulp configuration trying to automate [`logerr`](https://github.com/i-break-codes/logerr) deploying:

```js
const gulp = require('gulp')
const $ = require('gulp-load-plugins')()
const rollupPlugins = require('rollup-load-plugins')()
gulp.task('default', () => {
  return gulp.src('logerr.js')
    .pipe($.sourcemaps.init())
    .pipe($.rollup({
      entry: 'logerr.js',
      sourceMap: true,
      plugins: [
        rollupPlugins.babel(),
        rollupPlugins.uglify({
          output: {
            comments: (node, comment) => {
              return comment.line === 1
            }
          }
        })
      ]
    }))
    .pipe($.rename({
      suffix: '.min'
    }))
    .pipe($.sourcemaps.write('.'))
    .pipe(gulp.dest('./'))
})
```

All is ok but I want to preserve first “banner” comment from `logerr.js`:

```js
/**
 * logerr
 *
 * @category   logerr
 * @author     Vaibhav Mehta <vaibhav@decodingweb.com>
 * @copyright  Copyright (c) 2016 Vaibhav Mehta <https://github.com/i-break-codes>
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 * @version    1.2 Stable
 */
```

But I cannot. This comment just disappears after `rollup-plugin-uglify` + `rollup-plugin-babel` even if I set `{ output: { comments: true } }`. All comments is preserved but not first.

If I remove `rollup-plugin-babel` but use `rollup-plugin-uglify`, behaviour is expected: saved only first comment with my config.

If I remove `rollup-plugin-uglify` but use `rollup-plugin-babel`, behaviour is expected: first comment not removed.

**Comment by TrySound** [comment]
This plugin doesn't do anything with content. You can refer an issue to uglify repo.
