### ISSUE TITLE
Working with uglify harmony branch

### ISSUE THREAD

**Issue by antstanley** [TrySound/rollup-plugin-uglify#24]
To get it working with the Harmony branch of UglifyJS you need to install the harmony branch via NPM (note the npm docs are out of date on this)

`npm install --save-dev uglify-js-harmony`

and specify the harmony branch in your Rollup config

```
import { rollup } from 'rollup';
import uglify from 'rollup-plugin-uglify';
import { minify } from 'uglify-js-harmony';

rollup({
    entry: 'main.js',
    plugins: [
        uglify({}, minify)
    ]
});
```

**Comment by TrySound** [comment]
@antstanley It's not quite branch. It's just an npm package around this.
```
npm i mishoo/UglifyJS2#harmony -D
```
should work in the same way.
