### ISSUE TITLE
Use Harmony Release

### ISSUE THREAD

**Issue by jhabdas** [TrySound/rollup-plugin-uglify#25]
Uglify now has a release for Harmony/ESNext/ES6/ES2015 (SWIDT?). Anyway, it'd be nice if this plug-in used it by default. https://github.com/mishoo/UglifyJS2/releases/tag/harmony-v2.8.7

**Comment by TrySound** [comment]
@jhabdas It's not the third release, so isn't stable. Having it by default is a bit dangerous. Users should use it explicitly.
There's not different between unstable branch and unstable release.

**Comment by jhabdas** [comment]
@TrySound thanks for the info. I'm still trying to grok what the upgrade path looks like. FWIW I'm using it right now on a rollup using es modules, arrow functions, `fetch` and Promises with thenables and it's working well. Wasn't sure what to make of the `3.x` comment, but there is this if it makes a difference: https://github.com/lautis/uglifier/issues/108#issuecomment-282484859

Thanks for the quick response!

**Comment by TrySound** [comment]
You may pass any instance of uglify as a parameter
https://github.com/TrySound/rollup-plugin-uglify#warning

**Comment by jhabdas** [comment]
Yep, still not groking it. But that's okay.
