### ISSUE TITLE
Keep a CHANGELOG?

### ISSUE THREAD

**Issue by jhabdas** [TrySound/rollup-plugin-uglify#32]
I saw version `2.0.x` was released and went to look for a changelog but couldn't find it. Given it's a major I should assume breakage but how would I know what to fix? Will it support the move from `uglify-js-harmony` to `uglify-es` now that the prior is deprecated? Not sure without digging through the code and your mind.

I've provided some information to help easily create changelogs in the link below. It would be great to have one when taking upgrades to save digging through the source.

https://github.com/speedtracker/speedtracker/issues/56#issuecomment-298863896

See also: http://keepachangelog.com/en/0.3.0/

**Comment by TrySound** [comment]
https://github.com/TrySound/rollup-plugin-uglify/releases/tag/v2.0.0

**Comment by jhabdas** [comment]
Good enough

**Comment by jhabdas** [comment]
Thanks.
