### ISSUE TITLE
Error transforming bundle with 'uglify' plugin

### ISSUE THREAD

**Issue by nwpappas** [TrySound/rollup-plugin-uglify#37]
I am receiving the following error when I attempt to add the uglify plugin into my Rollup chain:

> [!] (uglify plugin) Error: Error transforming bundle with 'uglify' plugin: Unexpected token: punc (()

The rest of the error makes it unclear if this is ultimately a Rollup or Uglify issue:

> Error: Error transforming bundle with 'uglify' plugin: Unexpected token: punc (()
>     at error (/Users/pappas/Repositories/fleet/node_modules/rollup/dist/rollup.js:185:14)
>     at Promise.resolve.then.then.catch.err (/Users/pappas/Repositories/fleet/node_modules/rollup/dist/rollup.js:9217:5)
>     at <anonymous>

However, I only run into an issue with uglify in the plugins chain.

My config currently looks like the following:

```
import vue from 'rollup-plugin-vue';
import commonjs from 'rollup-plugin-commonjs';
import resolve from 'rollup-plugin-node-resolve';
import sass from 'rollup-plugin-sass';
import sassLint from 'rollup-plugin-sass-lint';
import uglify from 'rollup-plugin-uglify';
import serve from 'rollup-plugin-serve';

export default {
  name: 'Fleet',
  input: 'src/fleet-vue/main.js',
  globals: {
    vue: 'Vue',
    lodash: '_',
    'fuse.js': 'Fuse'
  },
  output: [
    {
      file: 'dist/js/fleet-vue.js',
      format: 'umd',
    },
    {
      file: 'dist/js/fleet-vue.esm.js',
      format: 'es'
    },
    {
      file: 'dist/js/fleet-vue.common.js',
      format: 'cjs'
    },
  ],
  plugins: [
    serve({
      open: true,
      verbose: true,
      contentBase: ['dist', '_site']
    }),
    sassLint({
      configFile: '.sass-lint.yml',
      failOnError: true
    }),
    resolve({
      jsnext: true,
      module: true
    }),
    commonjs(),
    vue(),
    sass({
      output: 'dist/css/fleet.css',
      options: {
        // node-sass options
      }
    }),
    uglify()
  ]
};

```

**Comment by meszaros-lajos-gyorgy** [comment]
Did this plugin get an update after the breaking changes of rollup, that has been added recently?
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32

**Comment by zlxbuzz** [comment]
ES2015 code?. Use `uglify-es`
```
import { minify } from 'uglify-es';
...
uglify({},minify)
```
