### ISSUE TITLE
ES6 classes fail to uglify

### ISSUE THREAD

**Issue by themre** [TrySound/rollup-plugin-uglify#38]
Hi,
I'm trying to uglify one lib and it's failing to uglify, probably due to ES6 syntax. Can anyone confirm if this is an issue with ES6 class or something else? Cannot get more info, pretty new with rollup. The error is this:
`[!] (uglify plugin) Error: Error transforming bundle with 'uglify' plugin: Unexpected token: name (NumberUtil)`

More info can be found here: https://github.com/codeofsumit/leaflet.pm/pull/255#issuecomment-346963003

**Comment by TrySound** [comment]
@themre this plugin uses uglify-js version (which do not support es6). There's a big section about this in readme https://github.com/TrySound/rollup-plugin-uglify#warning

**Comment by themre** [comment]
Great,thanks! Sorry for spam.
