### ISSUE TITLE
Sourcemaps from TypeScript?

### ISSUE THREAD

**Issue by Ne0nx3r0** [TrySound/rollup-plugin-uglify#41]
I'm using this plugin with others in this order:
rollup-plugin-css-only
rollup-plugin-sourcemaps
rollup-plugin-replace
rollup-plugin-resolve({jsnext: true,main: true})
rollup-plugin-commonjs
rollup-plugin-uglify

But this issue is without uglify I have TypeScript sourcemaps that come across and work normally, but when uglify is added the sourcemaps don't have the uglified variables, etc. in the debugger.  The lines still correspond, but when highlighting variables to see their value it says they are undefined since they've been renamed by uglify.

I seem to be failing at configuring uglify to provide sourcemaps, is there an order or option I'm missing here that would allow me to uglify but use the typescript sourcemaps?

**Comment by TrySound** [comment]
@Ne0nx3r0 Show your whole config

**Comment by Ne0nx3r0** [comment]
Worked it out, sourcemaps() just has to be placed after uglify() instead of 2nd in the plugins array.
