### ISSUE TITLE
TypeError: uglify is not a function

### ISSUE THREAD

**Issue by tomleadbettermsm** [TrySound/rollup-plugin-uglify#45]
Hi. Using the following gives an error in the cli: TypeError: uglify is not a function

```
import uglify from 'rollup-plugin-uglify';
export default {
  input: 'src/js/main.js',
  output: {
    file: 'build/js/bundle.js',
    format: 'cjs', // immediately-invoked function expression — suitable for <script> tags
    sourcemap: true
  },
  plugins: [
    uglify()
  ]  
};
```

This fixes the issue though:
`uglify.uglify()`

Not sure if I've done something wrong or if there is a defect with the version I'm using ("version": "4.0.0").

Thanks

**Comment by TrySound** [comment]
Changelog is clear about using named export.
https://github.com/TrySound/rollup-plugin-uglify/releases/tag/v4.0.0

**Comment by julmot** [comment]
@TrySound Please elaborate why uglify-es is no longer supported. I can't see any deprecations in uglify-es itself.

https://github.com/mishoo/UglifyJS2/tree/harmony

**Comment by TrySound** [comment]
https://github.com/mishoo/UglifyJS2/issues/3156
https://github.com/mishoo/UglifyJS2/issues/2447

Use terser for es6+
https://github.com/TrySound/rollup-plugin-terser

**Comment by ardivali** [comment]
Or you can change this line in the index file  ('.\node_modules\rollup-plugin-uglify\index.js') 
from
exports.uglify = uglify;
to
exports.default = uglify;
to keep
...
  plugins: [
    uglify()
  ]  
...

**Comment by TrySound** [comment]
@ardivali I'm not gonna change the api. I think it's right. Use this
```js
const { uglify } = require('rollup-plugin-uglify')
```

**Comment by TrySound** [comment]
or this
```
import { uglify } from 'rollup-plugin-uglify'
```

**Comment by TrySound** [comment]
Otherwise you need to do this ugly this
```js
const { default: uglify } = require('rollup-plugin-uglify');
const uglify = require('rollup-plugin-uglify').default;
```

**Comment by hex0gen** [comment]
it helped me:

`npm i uglify`

Another decision to the same error.
