### ISSUE TITLE
Switch to uglify-es?

### ISSUE THREAD

**Issue by moonglum** [TrySound/rollup-plugin-uglify#47]
Thanks for your great work on this plugin.

Have you seen uglify-es? It is created by the same author as uglify-js (it is even in the same repo) and it supports es6+. [You can find the documentation here](https://github.com/mishoo/UglifyJS2/tree/harmony). Maybe it makes sense to switch to this package to enable es6+ Syntax?

**Comment by TrySound** [comment]
Thanks but uglify-es is dead project. Use terser instead.

![image](https://user-images.githubusercontent.com/5635476/43612118-fee93f26-96b3-11e8-890d-21028b74c344.png)
![image](https://user-images.githubusercontent.com/5635476/43612185-3015a0ee-96b4-11e8-84a1-6adc53ef7dad.png)
![image](https://user-images.githubusercontent.com/5635476/43612207-4616ca08-96b4-11e8-9192-8d6bb4313133.png)

**Comment by moonglum** [comment]
Ok, thanks! Did not know that 👍
