### ISSUE TITLE
Best way to pass in options to the CLI?

### ISSUE THREAD

**Issue by rafaelrinaldi** [TrySound/rollup-plugin-uglify#5]
I was wondering what's the best way to pass in options to the CLI? I'm using [`rollupify`](https://github.com/nolanlawson/rollupify) and this is my current command:

```
$ browserify source/scripts -t [ rollupify --plugins [ rollup-plugin-uglify ]  ] -t [ babelify --presets [ es2015 ] ] -do public/bundle.js
```

**Comment by TrySound** [comment]
@rafaelrinaldi Why not just use rollup? I don't use and do not suggest this way. Ask in rollupify.

**Comment by rafaelrinaldi** [comment]
@TrySound Yeah, that's what I ended up doing. Thanks anyway.
