### ISSUE TITLE
Fails with (uglify plugin) TypeError: regex.test is not a function

### ISSUE THREAD

**Issue by pvdlg** [TrySound/rollup-plugin-uglify#51]
When passing an Uglify option that is a regex, Uglify fails with error `TypeError: regex.test is not a function` as it seems `rollup-plugin-uglify` somehow transform regexps into strings.
It might happen when passing the option object to the `jest-worker`.

Here is the config to reproduce:
```js
import { rollup } from "rollup";
import { uglify } from "rollup-plugin-uglify";

rollup({
  input: "main.js",
  plugins: [uglify({mangle: {properties: {regex: /^_/}}})]
});
```

**Comment by TrySound** [comment]
I get it. Thanks for reporting. Could you use v4 for now?

**Comment by xt0rted** [comment]
I just ran into a similar issue. Passing a regex to `options.comments` causes all comments to be left in the file, and if I try a function it doesn't get called. Downgrading to v4 works as expected. The same issue exists in `rollup-plugin-terser@2`.

**Comment by TrySound** [comment]
Gonna fix after next rollup release with new lifecycle hooks

**Comment by TrySound** [comment]
Fixed in https://github.com/TrySound/rollup-plugin-uglify/releases/tag/v6.0.0
