### ISSUE TITLE
Plugin doesn't work on Virtual Machines with ubuntu when numWorkers != 1

### ISSUE THREAD

**Issue by dumistoklus** [TrySound/rollup-plugin-uglify#53]
I tried to build my code on dev machine Windows - it works fine.

Then I tried to build code on VM (VirtualBox) with Ubuntu 16.04 and 18.04 build was stop without any error. Building was stopped on step "./js/article.ts → ./www/build/article.js..."

Step by step I found a heart of bug - "numWorkers". If I set numWorkers to "1" then building work fine. otherwise, stop without error.

**Comment by dumistoklus** [comment]
> Does it work when numWorkers is not set?

no

> This is the default value. Is it lying?
`import os from 'os';
os.cpus().length - 1`

I think it a problem place.
What happen if I have only one CPU?

**Comment by dumistoklus** [comment]
@TrySound well?

**Comment by TrySound** [comment]
It's jest bug. Fixed in master. For now you may specify `numWorkers` explicitly

```js
Math.max(1, os.cpus().length - 1)
```

Ref https://github.com/facebook/jest/issues/7181

**Comment by utatti** [comment]
So the following workaround fixes this issue.

```js
uglify({ numWorkers: 1 })
```

I think it's kinda critical, because it doesn't print any error and just silently fails to generate output.

**Comment by TrySound** [comment]
@utatti You may use `rollup-plugin-terser`. Terser is less buggy than uglify.

**Comment by TrySound** [comment]
Guys, I upgraded jest-worker to version which sets minimal numWorkers to 1. You may remove that option now.

I still recommend to migrate to terser.
