### ISSUE TITLE
Warning: transformBundle hook used by plugin uglify is deprecated

### ISSUE THREAD

**Issue by lukasoppermann** [TrySound/rollup-plugin-uglify#59]
Hey, 
thank you for working on this plugin. I just updated rollup to v1 and now get the following warning.

> uglify plugin: The transformBundle hook used by plugin uglify is deprecated. The renderChunk hook should be used instead.

It sounds like an easy fix.

**Comment by TrySound** [comment]
This plugin does not use deprecated stuff.
https://github.com/TrySound/rollup-plugin-uglify/blob/master/index.js#L27

**Comment by lukasoppermann** [comment]
Sorry, wrong repo.
