### ISSUE TITLE
Rollup v1

### ISSUE THREAD

**Issue by Havunen** [TrySound/rollup-plugin-uglify#60]
Hey!

I like this plugin, it would be nice to have this updated for rollup v1.

NPM is warning about out of range peer dependency 
`npm WARN rollup-plugin-uglify@6.0.0 requires a peer of rollup@>=0.66.0 <1 but none is installed. You must install peer dependencies yourself.`

**Comment by Havunen** [comment]
v6.0.1 seems to have fixed the issue! Thanks guys! 👍

**Comment by TrySound** [comment]
@Havunen I would recommend you to use terser instead. I have less trust to uglify team these days.
