### ISSUE TITLE
how to set option for double rollup.output

### ISSUE THREAD

**Issue by 5shell** [TrySound/rollup-plugin-uglify#66]
for example
output: [{
file: 'index.js'
},{
file: 'index.es.js'
}]
how can i set options of uglify, to make tow output files.
one file use uglify, and another don't use

and ps, when i using uglify, sometimes, running 'rollup -c', it will no response

**Comment by TrySound** [comment]
There is a solution in terser plugin. I recommend to use it instead of uglify.
https://github.com/TrySound/rollup-plugin-terser#includeexclude

**Comment by 5shell** [comment]
great. thanks
