### ISSUE TITLE
Work with `banner`

### ISSUE THREAD

**Issue by kentcdodds** [TrySound/rollup-plugin-uglify#7]
Given this config:

```js
import babel from 'rollup-plugin-babel'
import uglify from 'rollup-plugin-uglify'

export default {
  entry: 'index.js',
  plugins: [
    babel({
      exclude: 'node_modules/**'
    }),
    uglify()
  ],
  format: 'umd',
  moduleName: 'isEmailMaybe',
  sourceMap: true,
  banner: `/**
 * @name isEmailMaybe
 * @license MIT
 * @copyright (c) 2016 Kent C. Dodds
 * @author Kent C. Dodds <kent@doddsfamily.us> (kentcdodds.com)
 */`
}
```

The my licensing comment (from the banner) will be removed. I believe that by default uglify keeps this around, but with the current implementation of this plugin, it is removed.

**Comment by TrySound** [comment]
@kentcdodds Banner doesn't mean it should be saved. By default uglify do not preserve comments (only cli has one preset). You can try that one
```js
uglify({
  output: {
    comments: function(node, comment) {
        var text = comment.value;
        var type = comment.type;
        if (type == "comment2") {
            // multiline comment
            return /@preserve|@license|@cc_on/i.test(test);
        }
    }
  }
});
```
http://lisperator.net/uglifyjs/codegen

**Comment by kentcdodds** [comment]
> only cli has one preset

I didn't realize this. Thanks for the tip. Would you like me to file a PR to add this to the README?

**Comment by TrySound** [comment]
Would be great.
It's the problem of uglify itself. And I don't think any wrappers should add own functionality like gulp-uglify (which is very big).

**Comment by kentcdodds** [comment]
> Would be great.

Awesome. Will do. I think it's a common use-case, so it'd be handy to have it in the README.

> I don't think any wrappers should add own functionality

I agree with you :+1: 💯

**Comment by kentcdodds** [comment]
PR filed.

**Comment by mbostock** [comment]
Here’s another approach using Uglify’s output.preamble option:

```js
import uglify from "rollup-plugin-uglify";

const definition = require("./package.json");

export default {
  input: "index",
  plugins: [
    uglify({
      output: {
        preamble: `// Hello, I am the preamble!`
      }
    })
  ],
  output: {
    file: `dist/${definition.name}.min.js`,
    format: "umd",
    name: definition.name
  }
};
```
