### ISSUE TITLE
Uglify not working with esm, throws an error instead.

### ISSUE THREAD

**Issue by KillDozerX2** [TrySound/rollup-plugin-uglify#83]
![image](https://user-images.githubusercontent.com/29596786/84691559-5cd5a980-af12-11ea-82bf-a235c1eb4dde.png)

**Comment by TrySound** [comment]
See note in readme
![image](https://user-images.githubusercontent.com/5635476/84693953-06d42680-af51-11ea-82bb-1301c55c0b84.png)

**Comment by KillDozerX2** [comment]
Yeah, I'm an idiot. Didn't read the Readme. Sorry
